name: Deploy Css-grid site In DockerHub
on:
  push:
    branches: [ main ]
    paths: ['08_css-grid/**']
  pull_request:
    branches: [ main ]
    paths: ['08_css-grid/**']
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i && npm run build
        working-directory: 08_css-grid
      - uses: docker/setup-buildx-action@v3
        with:
          context: ./08_css-grid
          file: ./08_css-grid/Dockerfile
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./08_css-grid
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/css-grid-site:latest
