name: Deploy Svg Sprite App In DockerHub
on:
  push:
    branches: [ main ]
    paths: ['02_svg/**']
  pull_request:
    branches: [ main ]
    paths: ['02_svg/**']
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -a
      - uses: docker/setup-buildx-action@v3
      - working-directory: ./02_svg
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/svg-sprite-serve:latest
