name: Deploy Svg Sprite App In DockerHub
on:
  push:
    branches: [ main ]
    paths: ['02_svg/**']
  pull_request:
    branches: [ main ]
    paths: ['02_svg/**']
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -a
      - uses: docker/setup-buildx-action@v3
        with:
          context: ./02_svg
          file: ./02_svg/Dockerfile
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./02_svg
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/svg-sprite-serve:latest
